---
title: "Coverting data typles"
author: "NguyenHo"
date: "2025-01-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
num<-as.numeric(15L)
print(num)
print(class(num))
```

# Complate data
```{r}
x<-25-56i
print(x)
print(class(x))
```

```{r}
y<-as.numeric(x)
print(y)
```

```{r}
x<-as.numeric(TRUE)
print(x)
class(x)
```

```{r}
m<-"jhjh"
class(m)
```

```{r}
c<-as.numeric(m)
print(c)
```

```{r}
d<-"1234587"
class(d)
```

```{r}
e<-as.numeric(d)
print(e)
class(e)
```

```{r}
f<-"12345lopl"
class(f)
```


```{r}
g<-as.numeric(f)
print(g)
```

# Convert Numeric to Integer
```{r}
h<-12.54
class(h)
```

```{r}
i<-as.integer(h)
print(i)
```

```{r}
j<-52-69i
class(j)
```

```{r}
k<-as.integer(j)
print(k)
```

```{r}
z<-TRUE
class(z)
```

```{r}
q<-as.integer(z)
print(q)
```

```{r}
class(q)
```

```{r}
c<-"1245638456"
class(c)
```

```{r}
j<-as.integer(c)
print(j)
class(j)
```

```{r}
o<-"12547lkj"
class(o)
```

```{r}
n<-as.integer(o)
print(n)
```

# Convert data to complex
```{r}
x<-1.25
class(x)
```

```{r}
v<-as.complex(x)
print(v)
class(v)
```

```{r}
w<-25L
class(w)
```

```{r}
s<-as.complex(w)
print(s)
```

```{r}
f<-TRUE
class(f)
```

```{r}
g<-as.complex(f)
print(g)
```

```{r}
y<-"124583"
class(y)
```

```{r}
d<-as.complex(y)
print(d)
class(d)
```

```{r}
logi<-as.logical(0)
print(logi)
```

```{r}
logi<-as.logical(1254)
print(logi)
```

```{r}
s<-as.logical(-254)
print(s)
```

```{r}
as.logical("1254lkj")
```

```{r}
x=2.514
y<-as.character(x)
print(y)
```

```{r}
class(y)
```

```{r}
m_p<-25L
```

```{r}
k<-as.character(m_p)
k
```

```{r}
a<-TRUE
b<-as.character(a)
print(b)
```

